### PR TITLE
Segment script without page load

### PR DESCRIPTION
**Pull request by chama-ram**
This is a duplicate of the segment script to allow page load of different apps separately

### CODE REVIEW

**Review by jethroflanagan — CHANGES_REQUESTED** [review]
Please change the name to `segment_no_page_load.js` to avoid casing issues

**Review by michael616kriel — APPROVED** [review]

**Comment by chama-ram** [comment]
@jethroflanagan I saw that there is this line in the script: `analytics._writeKey="WGk0NXmhoqH5OVjoaJUU6Tmj9Ge6fFY6"`

Is it fine if I remove it? 
I will include two snippets on the spa side that will load the key and page

```
    analytics.load('${process.env.NEXT_STATIC_SEGMENT_WRITE_KEY}');
    analytics.page('Company: Candidate Preview List Action');
```

**Comment by jethroflanagan** [comment]
> @jethroflanagan I saw that there is this line in the script: `analytics._writeKey="WGk0NXmhoqH5OVjoaJUU6Tmj9Ge6fFY6"`
> 
> Is it fine if I remove it? I will include two snippets on the spa side that will load the key and page
> 
> ```
>     analytics.load('${process.env.NEXT_STATIC_SEGMENT_WRITE_KEY}');
>     analytics.page('Company: Candidate Preview List Action');
> ```

@chama-ram You need to keep it in so Segment runs correctly

**Review by jethroflanagan — APPROVED** [review]

**Review by jethroflanagan — CHANGES_REQUESTED** [review]
Please re-add the key

**Review by jethroflanagan — APPROVED** [review]

**Pull request merged**
